steps:
  # Build the Docker image (replace . with your source directory if needed)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/$PROJECT_ID/test-tf/my-image:latest', '.']
  # Tag the image with the commit SHA for easy tracking
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/test-tf/my-image:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/test-tf/my-image:latest']

  # Deploy to Cloud Run service (replace SERVICE_NAME with your actual service name)
  - name: 'gcr.io/cloud-builders/cloud-run'
    args:
      - deploy
      - --image
      - 'gcr.io/$PROJECT_ID/test-tf/my-image:$COMMIT_SHA'
      - --platform
      - 'managed'  # Specify managed Cloud Run for serverless execution
      - --region
      - 'us-central1'  # Change to your desired region
      - --service
      - 'bulid-test'

images:
  - 'gcr.io/$PROJECT_ID/test-tf/my-image'

options:
  logging: NONE  # Adjust logging level as needed
