steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image', '.']

  # Tag the Docker image with the commit SHA
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image:latest', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image:$COMMIT_SHA']

  # Push the latest tag to the Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image:latest']

  # Push the commit-specific tag to the Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'
    script: |
      gcloud run deploy cloudrunservice --image us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image --region us-central1 --platform managed --allow-unauthenticated

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image'

options:
  logging: NONE
