steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image', '.']
# Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image']
# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - '<YOUR_SERVICE_NAME>'  # Replace with your actual service name
  - '--image'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image:$COMMIT_SHA'  # Assuming you want to use commit SHA for versioning
  - '--region'
  - 'us-central1' # Replace with your desired region
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image'
options:
  logging: NONE
# test
