steps:
  # Build the Docker image (replace . with your source directory if needed)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image', '.']
    # Add a comment explaining the build step (optional)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image:latest', 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/test-tf/my-image'

options:
  logging: NONE
